const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const SYSTEM_REFERENCES=[
{id:'system-locked-rating',title:'What contributes to V4.4c ratings',category:'System rules',tags:'Beyer weights rankings best three jockey trainer',usage:'SCORING DOCUMENTATION',text:'V4.4c uses latest verified Beyer weight 40, best of latest three weight 22, PP jockey local win rate weight 7, PP trainer local win rate weight 8, and trainer context weight 12 for horses with one or two career starts. Missing components are omitted. Adjustments include field-relative figure, pace fit, rebound and lightly raced upside, capped at ±6 total. Raw scores determine order. First-time starters and missing verified evidence can force a race PASS. This document explains the locked model; importing reference files does not change its weights.'},
{id:'system-reference-use',title:'How reference-only information is used',category:'System rules',tags:'pedigree workouts class trips layoffs connections J1',usage:'DISPLAY / RESEARCH ONLY',text:'Uploaded PP workouts and pedigree are displayed as source notes in Pace & Ratings; they do not add points to V4.4c. Prior conditions, trip text, distance/surface matching and layoff proxies are displayed as context without a rating bonus. Joint jockey/trainer records support the pairing box but do not change V4.4c. J1 uses annual jockey records for a separate research ranking, not the default rating. Narrative cheat sheets are hypotheses for human review, not verified success rates. No reference is automatically read by the scoring engine just because it is in the Knowledge Base. Search a horse, jockey, trainer or angle here to review its source before deciding whether it deserves a separate frozen test.'},
{id:'system-pairing',title:'Jockey/trainer pairing evidence and limits',category:'Connections',tags:'top 12 Saratoga Brown Prat Franco pairing win place show',usage:'DISPLAY / RESEARCH ONLY',text:'The pairing box uses the completed 2026 Saratoga summer meet top 12 by wins as a prior-meet reference, not current Belmont standings. Pair win statistics from PP source records retain their local or all-track scope and period. Small samples are labeled. Joint second/third counts are unavailable where not provided. Pair recognition does not award rating points. Saratoga jockey/trainer cheat-sheet claims need independent verification; uploading a sheet does not certify its claims.'},
{id:'system-paper',title:'Paper wagering rules and limitations',category:'Wagering research',tags:'pick 3 exacta win bankroll A B PASS',usage:'RESEARCH ONLY',text:'Paper tickets are experimental. V4.4c ratings are not calibrated win probabilities. Best Value and automated wagering remain disabled. Pick 3 research v1 uses A: rank 1 plus rank 2 within two raw points; B: remaining top-three runners; AAA and exactly-one-B tickets. Any PASS leg means sequence PASS. Illustrative caps: $24 sequence, $30 combined daily outlay, $240 reserve from $300. These thresholds require untouched testing; higher hit rate alone does not prove profitability.'}
];
export function searchReferences(records,query,category='All',archived=false){
 const terms=String(query||'').toLowerCase().trim().split(/\s+/).filter(Boolean);
 return records.filter(r=>!!r.archived===archived&&(category==='All'||r.category===category)&&terms.every(t=>[r.title,r.category,r.tags,r.usage,r.text,r.fileName,r.source].join(' ').toLowerCase().includes(t)));
}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('nyraKnowledgeBase',1);r.onupgradeneeded=()=>r.result.createObjectStore('references',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function transact(db,mode,action){return new Promise((resolve,reject)=>{const tx=db.transaction('references',mode);const req=action(tx.objectStore('references'));let result;req.onsuccess=()=>result=req.result;tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
async function extract(file){
 if(/\.(txt|md)$/i.test(file.name))return file.text();
 if(/\.pdf$/i.test(file.name)){
  const pdfjs=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.min.mjs';
  const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;let text='';
  for(let i=1;i<=pdf.numPages;i++){const p=await pdf.getPage(i),c=await p.getTextContent();text+='\n[Page '+i+']\n'+c.items.map(x=>x.str+(x.hasEOL?'\n':' ')).join('');}await pdf.destroy();return text;
 }
 if(/\.docx$/i.test(file.name)){
  const {unzipSync,strFromU8}=await import('https://cdn.jsdelivr.net/npm/fflate@0.8.2/esm/browser.js');
  const files=unzipSync(new Uint8Array(await file.arrayBuffer()),{filter:f=>f.name==='word/document.xml'});
  if(!files['word/document.xml'])throw Error('DOCX body not found');
  const xml=new DOMParser().parseFromString(strFromU8(files['word/document.xml']),'application/xml');
  return [...xml.getElementsByTagNameNS('*','p')].map(p=>[...p.getElementsByTagNameNS('*','t')].map(t=>t.textContent).join('')).join('\n');
 }
 throw Error('Use PDF, DOCX, TXT or MD');
}
const fileBase64=blob=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.onerror=()=>reject(r.error);r.readAsDataURL(blob);});
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),60000);}
export async function initKnowledgeBase(context){
 const root=document.getElementById('knowledge');let db,records=[],objectURL;
 const el=id=>root.querySelector('#'+id),status=message=>el('kbStatus').textContent=message;
 root.innerHTML='<div class="grid"><div class="card span12"><div class="kicker">Horse racing reference library</div><h2>Knowledge Base</h2><p class="small muted">Search documents and system explanations. Uploads are saved on this browser/device and are not sent to the odds server. Export a backup to move them to another device. Uploading references does not change horse ratings.</p><div class="controls"><div style="grid-column:span 3"><label for="kbSearch">Search titles, tags and extracted document text</label><input id="kbSearch" type="search" placeholder="Chad Brown, pedigree, turf, Beyer…"></div><div><label for="kbCategory">Category</label><select id="kbCategory"><option>All</option><option>Connections</option><option>Pedigree</option><option>Workouts</option><option>Pace / trips</option><option>Wagering research</option><option>System rules</option><option>General reference</option></select></div><div><label for="kbArchived">View</label><select id="kbArchived"><option value="active">Active</option><option value="archived">Archived</option></select></div></div><div class="flex" style="margin-top:12px;flex-wrap:wrap"><button class="secondary" id="kbThisRace">Search this race’s top horse</button><button class="secondary" id="kbBackup">Export backup</button><label class="small">Restore backup <input id="kbRestore" type="file" accept=".json"></label></div><p id="kbStatus" class="small muted" role="status" aria-live="polite">Opening reference database…</p></div><div class="card span12"><h3>Upload reference material</h3><div class="controls"><div style="grid-column:span 2"><label for="kbFiles">PDF, DOCX, TXT or MD · maximum 20 MB each</label><input id="kbFiles" type="file" accept=".pdf,.docx,.txt,.md" multiple></div><div><label for="kbUploadCategory">Category</label><select id="kbUploadCategory"><option>General reference</option><option>Connections</option><option>Pedigree</option><option>Workouts</option><option>Pace / trips</option><option>Wagering research</option></select></div><div><label for="kbTags">Tags</label><input id="kbTags" placeholder="trainer, turf, Saratoga"></div><div style="grid-column:span 2"><label for="kbSource">Source / scope / year</label><input id="kbSource" placeholder="Author or provider; meet and year"></div></div><button class="primary" id="kbUpload" style="margin-top:12px">Add references</button><p class="tiny muted">Scanned PDFs without selectable text need searchable notes or OCR before full-text search can find their contents. Claims remain user-provided and unverified.</p></div><div class="card span12"><h3 id="kbCount">References</h3><div id="kbResults" class="stack"></div></div><div class="card span12 hidden" id="kbDetail"><button class="secondary" id="kbClose">Close reference</button><div id="kbDetailBody" style="margin-top:12px"></div></div></div>';
 try{db=await openDB();}catch(e){status('Database unavailable: '+e.message+'. Allow browser storage to use uploads.');return;}
 const refresh=async()=>{records=[...SYSTEM_REFERENCES.map(r=>({...r,builtin:true})),...await transact(db,'readonly',s=>s.getAll())];render();};
 function render(){const found=searchReferences(records,el('kbSearch').value,el('kbCategory').value,el('kbArchived').value==='archived');el('kbCount').textContent=found.length+' references';
  el('kbResults').innerHTML=found.map(r=>'<div class="note"><b>'+esc(r.title)+'</b> <span class="pill">'+esc(r.category)+'</span><div class="tiny muted">'+esc(r.usage)+' · '+esc(r.source||'Handicapper system documentation')+'</div><p class="small">'+esc((r.text||'No extracted text. Open the source or add searchable notes.').slice(0,260))+'</p><div class="tiny muted">'+esc(r.tags||'')+'</div><button class="secondary" data-open="'+esc(r.id)+'">Open reference</button></div>').join('')||'<p class="muted">No matching references.</p>';
  el('kbResults').querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>open(records.find(r=>r.id===b.dataset.open)));
 }
 function open(r){if(objectURL)URL.revokeObjectURL(objectURL);el('kbDetail').classList.remove('hidden');
  if(r.blob)objectURL=URL.createObjectURL(r.blob);
  el('kbDetailBody').innerHTML='<h3>'+esc(r.title)+'</h3><div class="small muted">'+esc(r.usage)+' · '+esc(r.source||'System documentation')+'</div>'+(r.blob?'<button class="secondary" id="kbDownload">Download original</button>':'')+(r.blob&&/\.pdf$/i.test(r.fileName)?'<iframe title="Reference PDF" src="'+objectURL+'" style="width:100%;height:520px;border:1px solid var(--line);margin-top:12px"></iframe>':'')+'<details open><summary>Searchable text / notes</summary><pre style="white-space:pre-wrap;overflow-wrap:anywhere;max-height:420px;overflow:auto" class="small">'+esc(r.text)+'</pre></details>'+(!r.builtin?'<label class="small">Edit searchable notes <textarea id="kbEditText" rows="8">'+esc(r.text)+'</textarea></label><button class="secondary" id="kbSaveNotes">Save notes</button> <button class="secondary" id="kbArchive">'+(r.archived?'Restore reference':'Archive reference')+'</button>':'');
  if(r.blob)el('kbDownload').onclick=()=>download(r.blob,r.fileName);
  if(!r.builtin){el('kbSaveNotes').onclick=async()=>{await transact(db,'readwrite',s=>s.put({...r,text:el('kbEditText').value}));await refresh();status('Searchable notes saved. Rating inputs unchanged.');};el('kbArchive').onclick=async()=>{await transact(db,'readwrite',s=>s.put({...r,archived:!r.archived}));el('kbDetail').classList.add('hidden');await refresh();status(r.archived?'Reference restored.':'Reference archived; restore it from Archived view.');};}
  el('kbDetail').scrollIntoView({behavior:'smooth',block:'start'});
 }
 el('kbClose').onclick=()=>{el('kbDetail').classList.add('hidden');if(objectURL)URL.revokeObjectURL(objectURL);};
 ['kbSearch','kbCategory','kbArchived'].forEach(id=>el(id).oninput=render);
 el('kbThisRace').onclick=()=>{const c=context(),top=c.rating.rankings[0];el('kbSearch').value=top?.name||'';render();status(top?'Searching '+top.name+'. You can also search its jockey, trainer or angle.':'This race has no ranked top horse. Enter a jockey, trainer or angle.');};
 el('kbUpload').onclick=async()=>{const files=[...el('kbFiles').files];if(!files.length){status('Choose reference files first.');return;}el('kbUpload').disabled=true;let added=0;
  try{for(const file of files){if(file.size>20*1024*1024)throw Error(file.name+' exceeds 20 MB');if(!/\.(pdf|docx|txt|md)$/i.test(file.name))throw Error('Unsupported file: '+file.name);status('Reading '+file.name+'…');let text='',warning='';try{text=await extract(file);if(!text.trim())warning='No searchable text; add notes.';}catch(e){warning='Text extraction failed: '+e.message+'. Original saved; add notes.';}await transact(db,'readwrite',s=>s.put({id:crypto.randomUUID(),title:file.name.replace(/\.[^.]+$/,''),fileName:file.name,mime:file.type,blob:file,text,category:el('kbUploadCategory').value,tags:el('kbTags').value,source:el('kbSource').value||'User-provided reference; scope unverified',usage:'REFERENCE ONLY · NO RATING POINTS',uploadedAt:new Date().toISOString(),archived:false,warning}));added++;}await refresh();status(added+' references saved. '+records.filter(r=>r.warning).map(r=>r.fileName+': '+r.warning).join(' '));el('kbFiles').value='';}
  catch(e){await refresh();status(added+' saved. '+e.message);}finally{el('kbUpload').disabled=false;}
 };
 el('kbBackup').onclick=async()=>{try{status('Preparing backup…');const rows=await transact(db,'readonly',s=>s.getAll()),refs=[];for(const r of rows){const {blob,...meta}=r;refs.push({...meta,data:await fileBase64(blob)});}download(new Blob([JSON.stringify({schema:'nyra-knowledge-v1',references:refs})],{type:'application/json'}),'NYRA_Knowledge_Base_Backup.json');status(rows.length+' uploaded references exported. Keep this backup for another browser or device.');}catch(e){status('Backup failed: '+e.message);}};
 el('kbRestore').onchange=async()=>{try{const f=el('kbRestore').files[0];if(!f)return;if(f.size>100*1024*1024)throw Error('Backup exceeds 100 MB');const data=JSON.parse(await f.text());if(data.schema!=='nyra-knowledge-v1'||!Array.isArray(data.references))throw Error('Unsupported backup');
  const rows=data.references.map(r=>{if(typeof r.id!=='string'||typeof r.title!=='string'||typeof r.data!=='string'||typeof r.text!=='string')throw Error('Invalid backup reference');if(r.data.length>28*1024*1024)throw Error('Reference exceeds size limit');const {data,...meta}=r;return {...meta,builtin:false,blob:new Blob([Uint8Array.from(atob(data),c=>c.charCodeAt(0))],{type:r.mime||'application/octet-stream'})};});
  await new Promise((resolve,reject)=>{const tx=db.transaction('references','readwrite');for(const row of rows)tx.objectStore('references').put(row);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});await refresh();status(rows.length+' references restored. Existing entries with the same IDs were replaced.');}catch(e){status('Restore failed: '+e.message);}
 };
 await refresh();status('Ready. '+(records.length-SYSTEM_REFERENCES.length)+' uploaded references saved on this browser. Built-in system notes are included.');
}
