import test from 'node:test';import assert from 'node:assert/strict';
import {evidenceProfile,evidenceWeightedRating,confidenceAdjustedTemperature,probabilityWeights} from './scoring-engine.js';
test('missing descriptive workout/pedigree text does not invent a numeric rating',()=>{assert.equal(evidenceWeightedRating([{value:null,weight:24},{value:null,weight:18}]),null)});
test('unknown career starts are labeled unknown and forced to low confidence',()=>{const e=evidenceProfile({lifeStarts:null,last:88,best:92,figs:[88,86,84],trainerAngles:'Dirt stats'});assert.equal(e.experience,'Starts unknown');assert.equal(e.confidence,'Low')});
test('first-time starter can reach medium but never high without race evidence',()=>{const e=evidenceProfile({lifeStarts:0,workText:'5f work',pedigree:'Sire / Dam',trainerAngles:'1st starter'});assert.equal(e.experience,'First-time starter');assert.equal(e.confidence,'Medium')});
test('first-time starter with only one support category stays low',()=>{assert.equal(evidenceProfile({lifeStarts:0,workText:'5f work'}).confidence,'Low')});
test('lightly raced runner is capped at medium',()=>{const e=evidenceProfile({lifeStarts:2,last:78,figs:[78,72],workText:'work',pedigree:'Sire / Dam',trainerAngles:'context'});assert.equal(e.experience,'Lightly raced');assert.equal(e.confidence,'Medium')});
test('established horse needs multiple direct figures for high confidence',()=>{assert.equal(evidenceProfile({lifeStarts:8,last:88,best:92,figs:[88,86,84]}).confidence,'High');assert.equal(evidenceProfile({lifeStarts:8,last:88,best:92,figs:[88]}).confidence,'Medium')});
test('lower confidence flattens fair-odds probability differences',()=>{const hi=probabilityWeights([{id:'a',rating:90,confidence:'High'},{id:'b',rating:70,confidence:'High'}]);const lo=probabilityWeights([{id:'a',rating:90,confidence:'Low'},{id:'b',rating:70,confidence:'Low'}]);assert.ok((hi[0].p-hi[1].p)>(lo[0].p-lo[1].p))});
