import test from 'node:test';import assert from 'node:assert/strict';import {priceEdge,requiredEdge,winDecision,exoticDecision,multiRaceDecision} from './wager-engine.js';
test('price edge compares available odds with fair odds',()=>assert.equal(Math.round(priceEdge('4/1','3/1')*100),25));
test('medium confidence requires a larger price cushion',()=>{assert.equal(requiredEdge('High'),.20);assert.equal(requiredEdge('Medium'),.30);assert.equal(requiredEdge('Low'),Infinity)});
test('low confidence cannot become a win play from price alone',()=>assert.equal(winDecision({odds:'20/1',fairOdds:'5/1',confidence:'Low',rating:80}).play,false));
test('medium confidence needs thirty percent edge',()=>{assert.equal(winDecision({odds:'4/1',fairOdds:'3/1',confidence:'Medium',rating:80}).play,false);assert.equal(winDecision({odds:'9/2',fairOdds:'3/1',confidence:'Medium',rating:80}).play,true)});
test('exotics pass when ratings are tight and there is no value runner',()=>assert.equal(exoticDecision([{id:1,rating:84,confidence:'High',odds:'2/1',fairOdds:'2/1'},{id:2,rating:82,confidence:'High',odds:'3/1',fairOdds:'3/1'},{id:3,rating:81,confidence:'Medium',odds:'4/1',fairOdds:'4/1'}]).play,false));
test('multi-race single requires high confidence and clear separation',()=>{assert.equal(multiRaceDecision([{rating:90,confidence:'High'},{rating:82,confidence:'High'}]).single,true);assert.equal(multiRaceDecision([{rating:90,confidence:'Medium'},{rating:80,confidence:'High'}]).single,false)});
test('low-confidence top choice cannot become an exotic key',()=>assert.equal(exoticDecision([{id:1,rating:95,confidence:'Low',odds:'10/1',fairOdds:'2/1'},{id:2,rating:84,confidence:'High',odds:'3/1',fairOdds:'3/1'},{id:3,rating:80,confidence:'Medium',odds:'8/1',fairOdds:'8/1'}]).play,false));
test('missing or malformed odds cannot manufacture value',()=>{assert.equal(winDecision({odds:'',fairOdds:'3/1',confidence:'High',rating:90}).play,false);assert.equal(winDecision({odds:'TBD',fairOdds:'3/1',confidence:'High',rating:90}).play,false);assert.equal(winDecision({odds:'4/1',fairOdds:null,confidence:'High',rating:90}).play,false)});
