import test from 'node:test';import assert from 'node:assert/strict';import {RULES,parseOdds,decideWin} from './win-value-gate.mjs';
const good={model:RULES.model,raceDecision:'RATEABLE',rank:1,rawScore:75,finalFieldVerified:true,surfaceVerified:true,selectionFrozen:true,scratched:false,cancelled:false,unconfirmedConditional:false,probabilityCalibrated:true,calibrationId:'synthetic-test-only',calibrationOutOfSample:true,confidenceVerified:true,confidence:'High',winProbability:0.4,odds:'2/1',quoteSource:'live-tote',quoteSourceId:'synthetic-test-only',now:1000000,quoteTime:990000,postTime:1120000,bankroll:300,dailyStaked:0,outstandingBets:0,alreadyBet:false};
test('Odds reject malformed, negative and nonfinite values',()=>{for(const x of ['2/1/4','-1/1','2/0','Infinity','2x','9'.repeat(400)+'/1','9'.repeat(400),-1,Infinity,null,''])assert.equal(parseOdds(x),null);assert.equal(parseOdds('5 - 2'),2.5);assert.equal(parseOdds('0/1'),0)});
test('Paper boundary is inclusive; live remains blocked',()=>{assert.equal(decideWin(good,{mode:'paper'}).decision,'PAPER_BET');assert.equal(decideWin(good).decision,'PASS');assert.equal(decideWin({...good,winProbability:.39999},{mode:'paper'}).decision,'PASS')});
test('Medium confidence requires thirty percent edge',()=>{assert.equal(decideWin({...good,confidence:'Medium'},{mode:'paper'}).decision,'PASS');assert.equal(decideWin({...good,confidence:'Medium',winProbability:1.3/3},{mode:'paper'}).decision,'PAPER_BET')});
const cases=[['model lock',{model:'V4.2'}],['race PASS',{raceDecision:'PASS'}],['only top1',{rank:2}],['unrated',{rawScore:null}],['field verification',{finalFieldVerified:false}],['surface verification',{surfaceVerified:false}],['selection freeze',{selectionFrozen:false}],['scratch',{scratched:true}],['cancelled',{cancelled:true}],['conditional',{unconfirmedConditional:true}],['uncalibrated',{probabilityCalibrated:false}],['no calibration provenance',{calibrationId:''}],['in-sample calibration',{calibrationOutOfSample:false}],['unverified confidence',{confidenceVerified:false}],['low confidence',{confidence:'Low'}],['bad probability',{winProbability:1}],['missing probability',{winProbability:null}],['malformed odds',{odds:'2/1/4'}],['morning line',{quoteSource:'morning-line'}],['final odds',{quoteSource:'final-result'}],['stale quote',{quoteTime:939999}],['future quote',{quoteTime:1000001}],['late bet',{postTime:1059999}],['bankroll floor',{bankroll:241}],['exposure cap',{dailyStaked:29}],['negative exposure',{dailyStaked:-1}],['outstanding bet',{outstandingBets:1}],['duplicate bet',{alreadyBet:true}]];
for(const [name,patch]of cases)test(name,()=>assert.equal(decideWin({...good,...patch},{mode:'paper'}).decision,'PASS'));
test('Exact bankroll and daily cap boundaries',()=>assert.equal(decideWin({...good,bankroll:242,dailyStaked:28},{mode:'paper'}).decision,'PAPER_BET'));
test('Missing boolean confirmations fail closed',()=>{const x={...good};delete x.scratched;assert.equal(decideWin(x,{mode:'paper'}).decision,'PASS')});
